# NumPy 1 - Array Practice

In [0]:
name = "Your name here"
"Name:" + name.upper()

## Instructions

**Use *NumPy* versions of math operations where available.** For example, use `np.tan(np.radians(85))` instead of `math.tan(math.radians(85))`. Note that *NumPy* does not have a factorial function so you will need to import it from the math module.

**Do not assign results to variables unless specified in an exercise's instructions.**

Finish the assignment by...
  - Saving your Jupyter Notebook and downloading it as a notebook (.ipynb) file (do not change the file name)
  - Submitting the notebook file to the NumPy 1 assignment via Canvas
  - Verifying that the auto grader marked each problem correct
  - Fixing errors and resubmitting as necessary until the due date

Your score will be determined by the auto grader results after the due date. Keep in mind that the auto grader may run additional tests on your final submission than were ran when the assignment was submitted.

**Execute the following cell to import *NumPy* and change display/print settings for *NumPy* arrays**

In [0]:
import numpy as np
import math
np.set_printoptions(precision=5, suppress=True)

**Exercise 1**

Create an array with the following elements: $ 8, 10/4, 12\times1.4, 51, \tan85^{\circ}, \sqrt{26}, 0.15$

Your completed array should have the following values...
```
array([ 8.     ,  2.5    , 16.8    , 51.     , 11.43005,  5.09902, 0.15   ])
```

In [0]:
# Write your exercise 1 code in this cell only


In [0]:
# Your exercise 1 solution will be autotested/scored here

**Exercise 2**

Create an array with the following elements: $\displaystyle \sqrt{15}\times10^3, \frac{25}{14-6^2}, \ln{(35)}/0.4^3, \frac{\sin{65^{\circ}}}{\cos{80^{\circ}}}, 129, \cos^2{(\pi/20)}$

Your completed array should have the following values...
```
array([3872.98335,   -1.13636,   55.55231,    5.21922,  129.     , 0.97553])
```

In [0]:
# Write your exercise 2 code in this cell only


In [0]:
# Your exercise 2 solution will be autotested/scored here

**Exercise 3**

Create an array that has the following elements: $\displaystyle 25.5, \frac{14\tan{58^{\circ}}}{(2.1^2 + 11)}, 6!, 2.7^4, 0.0375, \pi/5$

Your completed array should have the following values...
```
array([ 25.5    ,   1.45391, 720.     ,  53.1441 ,   0.0375 ,   0.62832])
```

In [0]:
# Write your exercise 3 code in this cell only


In [0]:
# Your exercise 3 solution will be autotested/scored here

**Exercise 4**

Create an array that has the following elements: $\displaystyle \frac{32}{3.2^2}, \sin^2{35^{\circ}}, 6.1, \ln(29^2), 0.00552, \ln^2{29}, 133 $

Your completed array should have the following values...
```
array([  3.125  ,   0.32899,   6.1    ,   6.73459,   0.00552,  11.33868, 133.     ])
```

In [0]:
# Write your exercise 4 code in this cell only


In [0]:
# Your exercise 4 solution will be autotested/scored here

**Exercise 5**

Define the variables $x$ = 0.85, $y$ = 12.5, and then use them to create an array with the following elements: $y, y^x, \ln(y/x), x\times y, x+y$

Your completed array should have the following values...
```
array([12.5    , 10.625  ,  2.68825, 10.625  , 13.35   ])
```

In [0]:
# Write your exercise 5 code in this cell only


In [0]:
# Your exercise 5 solution will be autotested/scored here

**Exercise 6**

Define the variables $a$ = 3.5, $b$ = -6.4, and then use them to create an array with the following elements: $a, a^2, a/b, a\cdot b, \sqrt{a}$

Your completed array should have the following values...
```
array([  3.5    ,  12.25   ,  -0.54688, -22.4    ,   1.87083])
```

In [0]:
# Write your exercise 6 code in this cell only


In [0]:
# Your exercise 6 solution will be autotested/scored here

#### Note: Use `np.arange()` or `np.linspace()` for exercises 7 through 10

**Exercise 7**
    
Create an array in which the first element is 1 and the last element is 43 with an increment of 6, i.e. (1, 7, 13, ... , 43) without manually typing each value.

In [0]:
# Write your exercise 7 code in this cell only


In [0]:
# Your exercise 7 solution will be autotested/scored here

**Exercise 8**

Create an array with 11 equally spaced elements in which the first element is 96 and the last element is 2 without manually typing each value.

Your completed array should have the following values...
```
array([96. , 86.6, 77.2, 67.8, 58.4, 49. , 39.6, 30.2, 20.8, 11.4,  2. ])
```

In [0]:
# Write your exercise 8 code in this cell only


In [0]:
# Your exercise 8 solution will be autotested/scored here

**Exercise 9**

Create an array in which the first element is 26, the elements decrease with an increment of -3.6, and the last element is -10 without typing each value.

Your completed array should have the following values...
```
array([ 26. ,  22.4,  18.8,  15.2,  11.6,   8. ,   4.4,   0.8,  -2.8, -6.4, -10. ])
```

In [0]:
# Write your exercise 9 code in this cell only


In [0]:
# Your exercise 9 solution will be autotested/scored here

**Exercise 10**

Create an array with 9 equally spaced elements in which the first element is -34 and the last element is -7 without manually typing each value.

Your completed array should have the following values...
```
array([-34.   , -30.625, -27.25 , -23.875, -20.5  , -17.125, -13.75 , -10.375,  -7.   ])
```

In [0]:
# Write your exercise 10 code in this cell only


In [0]:
# Your exercise 10 solution will be autotested/scored here

**Exercise 11**

Use the `np.arange()` and `np.append()` functions together in one expression to create an array named `b` such that `b` has the values [0, 2, 4, 6, 8, 10, 12, 9, 6, 3, 0]. Print `b` after creation.

In [0]:
# Write your exercise 11 code in this cell only


In [0]:
# Your exercise 11 solution will be autotested/scored here

**Exercise 12**

Create the following 2D array `A` by using the `np.linspace()` and `np.arange()` functions to fill the values. Print `A` after creation.

$\qquad\displaystyle A = \left[\begin{array}{ccccccc} 130 & 110 & 90 & 70 & 50 & 30 & 10 \\
1.0 & 2.83\bar3 & 4.66\bar6 & 6.5 & 8.33\bar3 & 10.16\bar6 & 12.0 \\
12 & 22 & 32 & 42 & 52 & 62 & 72\end{array} \right]$

*Notice that the second row values have repeating digits. This is probably **not** a good place to use a specific step size.*

In [0]:
# Write your exercise 12 code in this cell only


In [0]:
# Your exercise 12 solution will be autotested/scored here

**Exercise 13**

Create three arrays: $a$ = [3, -1, 5, 11, -4, 2], $b$ = [7, -9, 2, 13, 1, -2], and $c$ = [-2, 4, -7, 8, 0, 9]

By slicing the three arrays, create a $3\times4$ two-dimensional array such that the first, second, and third rows consist of the last four elements of the arrays $a$, $b$, and $c$ respectively. Your completed array should have the following values...

```
array([[ 5, 11, -4,  2],
       [ 2, 13,  1, -2],
       [-7,  8,  0,  9]])
```

In [0]:
# Create the initial arrays `a`, `b`, and `c` for exercises 13 and 14 in this cell


In [0]:
# Write your exercise 13 slicing code in this cell only


In [0]:
# Your exercise 13 solution will be autotested/scored here

**Exercise 14**

Using the arrays from **13**, create a $6\times3$ two-dimensional array such that the first, second, and third columns are the arrays $b$, $c$, and $a$ respectively.

*Hint: the `.T` method helps.*

Your completed array should have the following values...
```
array([[ 7, -2,  3],
       [-9,  4, -1],
       [ 2, -7,  5],
       [13,  8, 11],
       [ 1,  0, -4],
       [-2,  9,  2]])
```

In [0]:
# Write your exercise 14 code in this cell only


In [0]:
# Your exercise 14 solution will be autotested/scored here

**Exercise 15**

Create the following 2D array by first using a **single** `np.arange()` and/or `np.linspace()` to create **one 1D array** with **all** of the values present then change its shape with the `.reshape()` method. Print `A` after creating the array.

$\qquad\displaystyle A = \left[ \begin{array}{cccccc} 
36 & 34 & 32 & 30 & 28 & 26 \\
24 & 22 & 20 & 18 & 16 & 14 \\
12 & 10 & 8 & 6 & 4 & 2 \end{array}\right] $

Then use slicing do each of the following in their own code cells:
- Create a six-element array that contains the elements of the second row of $A$. Your completed array should have the following values...
    ```
    array([24, 22, 20, 18, 16, 14])
    ```
- Create a three-element array that contains the elements of the sixth column of $A$. Your completed array should have the following values...
    ```
    array([26, 14,  2])
    ```
- Create a five-element array that contains the first two elements of the third row and the last three elements of the first row of $A$. Your completed array should have the following values...
    ```
    array([12, 10, 30, 28, 26])
    ```

In [0]:
# Create the exercise 15 initial multi-row array in this cell only


In [0]:
# Your exercise 15 initial array solution will be autotested/scored here

In [0]:
# Write your code for the first part of exercise 15 in this cell only


In [0]:
# Your exercise 15 part 1 solution will be autotested/scored here

In [0]:
# Write your code for the second part of exercise 15 in this cell only


In [0]:
# Your exercise 15 part 2 solution will be autotested/scored here

In [0]:
# Write your code for the third part of exercise 15 in this cell only


In [0]:
# Your exercise 15 part 3 solution will be autotested/scored here

**Exercise 16**

Create the following 2D array by using `np.append()`, `np.zeros()`, `np.arange()`, the `.reshape()` method, and `.T` only in one single expression. Each function or method should only be used once.

$\qquad\displaystyle \left[\begin{array}{ccccc}
0 & 0 & 0 & 0 & 8 \\
0 & 0 & 0 & 0 & 7 \\
0 & 0 & 0 & 0 & 6 \end{array} \right]$

In [0]:
# Write your exercise 16 code in this cell only


In [0]:
# Your exercise 16 solution will be autotested/scored here

**Exercise 17**

Use a single expression to create a six element 1D array such that the first value is 1.1 and the last value is 6.6 and all of the others are zero. Do not directly type the zeros; use NumPy functions or methods.

*Hint: this may be a good place to try out* `np.insert()` *or* `np.hstack()`.

Your completed array should have the following values...
```
array([1.1, 0. , 0. , 0. , 0. , 6.6])
```

In [0]:
# Write your exercise 17 code in this cell only


In [0]:
# Your exercise 16 solution will be autotested/scored here

**Wrap it up**

Complete the finishing tasks stated in the instructions.
